#!/usr/bin/env bash
# Script installs and configures Nginx on an Ubuntu server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!"|sudo tee  /var/www/html/index.html
sudo /etc/init.d/nginx restart