#!/usr/bin/env bash
# Script configures a new Ubuntu server and creates a custom 404 error page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
err_msg='\n\t error_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'
sudo sed -i "/server_name _;/ a \ $err_msg" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart