#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y  install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.2

sudo apt-get -y install haproxy=2.2.\*

cat >> sudo /etc/haproxy/haproxy.cfg << EOF

frontend My_server
	bind *:80
	mode http
	default_backend web_server

backend web_server
	balance roundrobin
	mode http
	server web-01 54.144.150.74:80 check
	server web-02 3.84.222.21:80 check

EOF

sudo service haproxy restart
