#!/usr/bin/env bash
# change domain resolve ips
# from 127.0.0.1=localhost to 127.0.0.2
# from 157.240.11.35=facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
